<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.9.6.0-alpha</Version>
    <Title>Lazulite.LinearAlgebra</Title>
    <Authors>raphael286</Authors>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>A float-based linear algebra extension package for Lazulite.</Description>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="\" />
    <!-- Write a special readme for this at some point -->
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Raphael.Lazulite" Version="1.9.6-alpha" />
  </ItemGroup>
</Project>