<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.6</Version>
    <Title>Lazulite</Title>
    <Authors>Julian Lavelle</Authors>
    <Description>Fast and powerful GPU acceleration for C#.</Description>
    <PackageProjectUrl>https://github.com/lavellex86/Lazulite</PackageProjectUrl>
    <RepositoryUrl>https://github.com/lavellex86/Lazulite</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageReleaseNotes>New README</PackageReleaseNotes>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ILGPU" Version="1.5.3" />
    <PackageReference Include="ILGPU.Algorithms" Version="1.5.3" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="../LICENSE" Pack="true" PackagePath="" />
    <None Include="../README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
