<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>Raphael.Calc32</PackageId>
    <Title>Raphael.Calc32</Title>
    <Version>2.2.2.0</Version>
    <Authors>Raphael</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raphael.Linalg32" Version="2.2.2" />
  </ItemGroup>

</Project>
