<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>1.9.1-alpha</Version>
        <Title>Lazulite</Title>
        <Authors>raphael286</Authors>
        <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ILGPU" Version="1.5.3" />
      <PackageReference Include="ILGPU.Algorithms" Version="1.5.3" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

</Project>
