<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Linalg32</Title>
    <Authors>Julian Lavelle</Authors>
    <Description>A float-based linear algbra extension library for Lazulite.</Description>
    <PackageProjectUrl>https://github.com/lavellex86/Lazulite</PackageProjectUrl>
    <RepositoryUrl>https://github.com/lavellex86/Lazulite.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Version>2.4.2</Version>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageReleaseNotes>Final batch of ops</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ILGPU" Version="1.5.3" />
    <PackageReference Include="ILGPU.Algorithms" Version="1.5.3" />
    <PackageReference Include="Lavelle.Lazulite" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../LICENSE" Pack="true" PackagePath="" />
    <None Include="../README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
