<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Linalg32</Title>
    <Authors>Julian Lavelle</Authors>
    <Description>A float-based linear algbra extension library for Lazulite.</Description>
    <PackageProjectUrl>https://github.com/lavellex86/Lazulite</PackageProjectUrl>
    <RepositoryUrl>https://github.com/lavellex86/Lazulite.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Version>2.6.0</Version>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageReleaseNotes>Update to lazulite 2.6</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lavelle.Lazulite" Version="2.6.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../LICENSE" Pack="true" PackagePath="" />
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
