<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Linalg32</Title>
    <Authors>raphael286</Authors>
    <Description>A float-based linear algbra extension library for Lazulite.</Description>
    <PackageProjectUrl>https://github.com/raphael286/Lazulite</PackageProjectUrl>
    <RepositoryUrl>https://github.com/raphael286/Lazulite.git</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <Version>2.0.2.7</Version>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>Narrowcast addition for matrix and vector</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ILGPU" Version="1.5.3" />
    <PackageReference Include="ILGPU.Algorithms" Version="1.5.3" />
    <PackageReference Include="Raphael.Lazulite" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../LICENSE" Pack="true" PackagePath="" />
    <None Include="../README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
