<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>Lavelle.Calc32</PackageId>
    <Title>Lavelle.Calc32</Title>
    <Version>2.6.0.0</Version>
    <Authors>Julian Lavelle</Authors>
    <Description>Numerical integration and differentiation for C#, built on Lazulite.</Description>
    <PackageProjectUrl>https://github.com/lavellex86/Lazulite</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/lavellex86/Lazulite.git</RepositoryUrl>
    <PackageReleaseNotes>release!</PackageReleaseNotes>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lavelle.Linalg32" Version="2.6.0" />
  </ItemGroup>

</Project>
